# Generated by Django 6.0.2 on 2026-02-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50, verbose_name='Device ID')),
                ('recorded_at', models.DateTimeField(db_index=True, verbose_name='Time Measured')),
                ('rssi', models.SmallIntegerField(blank=True, null=True, verbose_name='RSSI')),
                ('snr', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='SNR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time Created in DB')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('altitude_m', models.SmallIntegerField(blank=True, null=True, verbose_name='Altitude')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp(C)')),
                ('humidity_pct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Humidity(%)')),
                ('pressure_hpa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pressure(hPa)')),
                ('lux_lx', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lux(lx)')),
                ('water_distance_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='WaterLevel(mm)')),
                ('raw_json', models.JSONField(blank=True, null=True, verbose_name='Raw data')),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data List',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
