import random
from datetime import timedelta
from django.core.management.base import BaseCommand
from django.utils import timezone
from faker import Faker
from steamapi.models import tblSensorData

class Command(BaseCommand):
    help = 'Generate dummy data'

    def add_arguments(self, parser):
        parser.add_argument( '--clear', action='store_true', help='Delete all dummy data', )

    def handle(self, *args, **options):

        if options['clear']:
            count = tblSensorData.objects.all().count()
            tblSensorData.objects.all().delete()
            self.stdout.write(self.style.SUCCESS(f'Successfully deleted {count} records.'))
            return

        fake = Faker()
        device_id = "SN-WATER-001"
        now = timezone.now()

        self.stdout.write(f"Generating data for {device_id}...")

        # Generate data 144 count per 10 min
        for i in range(144):
            recorded_at = now - timedelta(minutes=10 * i)

            tblSensorData.objects.create(
                device_id=device_id,
                recorded_at=recorded_at,
                rssi=random.randint(-120, -90),
                snr=random.uniform(-10, 10),
                latitude=39.92 + random.uniform(-0.01, 0.01),
                longitude=141.02 + random.uniform(-0.01, 0.01),
                altitude_m=random.randint(200, 250),
                temperature_c=20.0 + 5.0 * random.uniform(-1, 1),
                humidity_pct=random.randint(40, 80),
                pressure_hpa=1013,
                lux_lx=random.randint(0, 50000) if 6 <= recorded_at.hour <= 18 else 0,
                water_distance_mm=3000 - (i * 2) + random.randint(-5, 5),
                raw_json={"dummy": True, "note": "generated by script"}
            )

        self.stdout.write(self.style.SUCCESS('Successfully generated 144 records.'))